### ISSUE TITLE
Travis CI runs invalid build/test process

### ISSUE THREAD

**Issue by thevulch** [Planteome/planteome-data-visualization#25]
As seen in #17, the CI isn't building/testing the project right. It would be very useful, though, so this needs to be fixed.

**Comment by elserj** [comment]
I attempted to add a .travis.yml file in commit beed7a1, but it still isn't correct.  Do you guys know what stuff needs to go in there?  It fails because we don't have any make targets.  I'll keep searching to see if I can figure out what we are supposed to have there.  What kind of stuff do you want the travis job to look for?  Just a "lint" check?

**Comment by thevulch** [comment]
For now, could the CI just pass vacuously? I miss closing issues via commit messages :~).

**Comment by elserj** [comment]
Took a bit to figure it out, but I got a working travis CI check on master.  You can probably follow what I did the following commits to recreate in branch viz:
069679878c6581449ac005a7c042bb1e4ed29895
e3006e4a3ca7390b98bb72ab26611abee28d0107
7989a436452a7de6446da19853406e2bb4e4fea7

I don't think you need the last one that installed the node_modules, as that should be available now.

At this point, I only set it to check master:EnrichmentAnalysis/project/js/funcs.js as I had to make some changes before the jshint would actually succeed.  To have it check all js files, change package.json to *.js rather than just funcs.js.  I'm not sure how this affects branches, but I believe the branch needs to be added to package.json, but I can't find where I thought I saw that anymore.

**Comment by elserj** [comment]
Also done to viz branch now via commit 643506882b0177e9bdeab43d8236d77357a5d914

Note, only set it up to check funcs.js.  I tried to do it for main.js but there were too many errors for it to pass.  I will let you worry about getting that one to pass.

To test it out on your machine, run the following from the top of the repo:
./node_modules/.bin/jshint EnrichmentAnalysis/project/js/main.js

You will get a list of errors that will need to be fixed before it can be added to the travis job.  Some can be fixed with comments at the top of the file to jshint, see funcs.js for examples.

After getting them all fixed and jshint returns nothing, you can add it to the package.json file to have it checked by changing line 7 to:
 "test": "jshint EnrichmentAnalysis/project/js/funcs.js EnrichmentAnalysis/project/js/main.js"

This should make travis check both files.
