### ISSUE TITLE
Technology Review & Selection

### ISSUE THREAD

**Issue by thevulch** [Planteome/planteome-data-visualization#7]
Hope this isn't too late, but we should probably keep a list somewhere on what tech we are using & what environments we are testing in.

We need to decide several things:
- [ ] What libraries are we using?
- [ ] What browsers (and specific versions) are we supporting? Do we have nonfunctional requirements that answer this for us, or do we have to decide?
- [x] Make a doc for keeping track of our decisions

**Comment by TheVulch** [comment]
@qubotong I partially made this task because I saw that you were calling jQuery-syntax code (`$.` notation)...are we using jQuery?

**Comment by qubotong** [comment]
@TheVulch Yes, I use little jQuery to make coding easier, since the jQuery is pretty good at supporting all browsers, we should be fine. For now, I think the browser support is not a big problem, but when we start use some js libraries to implement the visualization, which is only supported by HTML 5, we should definitely put the information somewhere.

**Comment by qubotong** [comment]
I added one README under the project folder, please feel free to add anything you think is needed.

**Comment by TheVulch** [comment]
@qubotong are we supporting old browsers without ES6 support, or just evergreen browsers? We should decide which visualization library we are using - this could decide it for us.
